[package]
name = "kvp"
version = "1.0.0"
edition = "2021"

authors = ["John Harry Kelly <johnharrykelly@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
